///////////////////////// Teacher action types ////////////////////////

//Login
export const FETCH_USER_LOGIN_DETAILS = "FETCH_USER_LOGIN_DETAILS";
export const FETCH_USER_LOGIN_DETAILS_SUCCESS =
  "FETCH_USER_LOGIN_DETAILS_SUCCESS";
export const FETCH_USER_LOGIN_DETAILS_FAILURE =
  "FETCH_USER_LOGIN_DETAILS_FAILURE";

//Forgot password
export const USER_FORGOT_PASSWORD = "USER_FORGOT_PASSWORD";
export const USER_FORGOT_PASSWORD_SUCCESS = "USER_FORGOT_PASSWORD_SUCCESS";
export const USER_FORGOT_PASSWORD_FAILURE = "USER_FORGOT_PASSWORD_FAILURE";

//Signup
export const USER_SIGN_UP = "USER_SIGN_UP";
export const USER_SIGN_UP_SUCCESS = "USER_SIGN_UP_SUCCESS";
export const USER_SIGN_UP_FAILURE = "USER_SIGN_UP_FAILURE";

//Reset Password
export const USER_RESET_PASSWORD = "USER_RESET_PASSWORD";
export const USER_RESET_PASSWORD_SUCCESS = "USER_RESET_PASSWORD_SUCCESS";
export const USER_RESET_PASSWORD_FAILURE = "USER_RESET_PASSWORD_FAILURE";

//Fetch all student data
export const FETCH_ALL_STUDENTS_DATA = "FETCH_ALL_STUDENTS_DATA";
export const FETCH_ALL_STUDENTS_DATA_SUCCESS =
  "FETCH_ALL_STUDENTS_DATA_SUCCESS";
export const FETCH_ALL_STUDENTS_DATA_FAILURE =
  "FETCH_ALL_STUDENTS_DATA_FAILURE";

//Fetch varified student data
export const FETCH_VARIFIED_STUDENTS_DATA = "FETCH_VARIFIED_STUDENTS_DATA";
export const FETCH_VARIFIED_STUDENTS_DATA_SUCCESS =
  "FETCH_VARIFIED_STUDENTS_DATA_SUCCESS";
export const FETCH_VARIFIED_STUDENTS_DATA_FAILURE =
  "FETCH_VARIFIED_STUDENTS_DATA_FAILURE";

//Fetch student details
export const FETCH_STUDENTS_DETAILS = "FETCH_STUDENTS_DETAILS";
export const FETCH_STUDENTS_DETAILS_SUCCESS = "FETCH_STUDENTS_DETAILS_SUCCESS";
export const FETCH_STUDENTS_DETAILS_FAILURE = "FETCH_STUDENTS_DETAILS_FAILURE";

//Create exam
export const CREATE_EXAM = "CREATE_EXAM";
export const CREATE_EXAM_SUCCESS = "CREATE_EXAM_SUCCESS";
export const CREATE_EXAM_FAILURE = "CREATE_EXAM_FAILURE";

export const CREATED_EXAM_BODY = "CREATED_EXAM_BODY";

//View exam
export const VIEW_EXAM = "VIEW_EXAM";
export const VIEW_EXAM_SUCCESS = "VIEW_EXAM_SUCCESS";
export const VIEW_EXAM_FAILURE = "VIEW_EXAM_FAILURE";

export const UPDATE_VIEW_EXAM = "UPDATE_VIEW_EXAM";

// Delete exam
export const DELETE_EXAM = "DELETE_EXAM";
export const DELETE_EXAM_SUCCESS = "DELETE_EXAM_SUCCESS";
export const DELETE_EXAM_FAILURE = "DELETE_EXAM_FAILURE";

// View exam in details
export const VIEW_EXAM_DETAILS = "VIEW_EXAM_DETAILS";
export const VIEW_EXAM_DETAILS_SUCCESS = "VIEW_EXAM_DETAILS_SUCCESS";
export const VIEW_EXAM_DETAILS_FAILURE = "VIEW_EXAM_DETAILS_FAILURE";

// Edit exam details
export const EDIT_EXAM_DETAILS = "EDIT_EXAM_DETAILS";
export const EDIT_EXAM_DETAILS_SUCCESS = "EDIT_EXAM_DETAILS_SUCCESS";
export const EDIT_EXAM_DETAILS_FAILURE = "EDIT_EXAM_DETAILS_FAILURE";

///////////////////////// Student action types ////////////////////////

//Fetch exam for student details
export const FETCH_EXAM_STUDENTS_DETAILS = "FETCH_EXAM_STUDENTS_DETAILS";
export const FETCH_EXAM_STUDENTS_DETAILS_SUCCESS =
  "FETCH_EXAM_STUDENTS_DETAILS_SUCCESS";
export const FETCH_EXAM_STUDENTS_DETAILS_FAILURE =
  "FETCH_EXAM_STUDENTS_DETAILS_FAILURE";

//Fetch exam paper
export const FETCH_EXAM_PAPER = "FETCH_EXAM_PAPER";
export const FETCH_EXAM_PAPER_SUCCESS = "FETCH_EXAM_PAPER_SUCCESS";
export const FETCH_EXAM_PAPER_FAILURE = "FETCH_EXAM_PAPER_FAILURE";

//Submit exam paper
export const SUBMIT_EXAM_PAPER = "SUBMIT_EXAM_PAPER";
export const SUBMIT_EXAM_PAPER_SUCCESS = "SUBMIT_EXAM_PAPER_SUCCESS";
export const SUBMIT_EXAM_PAPER_FAILURE = "SUBMIT_EXAM_PAPER_FAILURE";

//Fetch student profile
export const FETCH_STUDENT_PROFILE = "FETCH_STUDENT_PROFILE";
export const FETCH_STUDENT_PROFILE_SUCCESS = "FETCH_STUDENT_PROFILE_SUCCESS";
export const FETCH_STUDENT_PROFILE_FAILURE = "FETCH_STUDENT_PROFILE_FAILURE";

// Update student profile
export const UPDATE_STUDENT_PROFILE = "UPDATE_STUDENT_PROFILE";
export const UPDATE_STUDENT_PROFILE_SUCCESS = "UPDATE_STUDENT_PROFILE_SUCCESS";
export const UPDATE_STUDENT_PROFILE_FAILURE = "UPDATE_STUDENT_PROFILE_FAILURE";
