//Login
export const FETCH_USER_LOGIN_DETAILS = "FETCH_USER_LOGIN_DETAILS";
export const FETCH_USER_LOGIN_DETAILS_SUCCESS =
  "FETCH_USER_LOGIN_DETAILS_SUCCESS";
export const FETCH_USER_LOGIN_DETAILS_FAILURE =
  "FETCH_USER_LOGIN_DETAILS_FAILURE";

//Forgot password
export const USER_FORGOT_PASSWORD = "USER_FORGOT_PASSWORD";
export const USER_FORGOT_PASSWORD_SUCCESS = "USER_FORGOT_PASSWORD_SUCCESS";
export const USER_FORGOT_PASSWORD_FAILURE = "USER_FORGOT_PASSWORD_FAILURE";

//Signup
export const USER_SIGN_UP = "USER_SIGN_UP";
export const USER_SIGN_UP_SUCCESS = "USER_SIGN_UP_SUCCESS";
export const USER_SIGN_UP_FAILURE = "USER_SIGN_UP_FAILURE";

//Reset Password
export const USER_RESET_PASSWORD = "USER_RESET_PASSWORD";
export const USER_RESET_PASSWORD_SUCCESS = "USER_RESET_PASSWORD_SUCCESS";
export const USER_RESET_PASSWORD_FAILURE = "USER_RESET_PASSWORD_FAILURE";

//Fetch all student data
export const FETCH_ALL_STUDENTS_DATA = "FETCH_ALL_STUDENTS_DATA";
export const FETCH_ALL_STUDENTS_DATA_SUCCESS =
  "FETCH_ALL_STUDENTS_DATA_SUCCESS";
export const FETCH_ALL_STUDENTS_DATA_FAILURE =
  "FETCH_ALL_STUDENTS_DATA_FAILURE";

//Fetch varified student data
export const FETCH_VARIFIED_STUDENTS_DATA = "FETCH_VARIFIED_STUDENTS_DATA";
export const FETCH_VARIFIED_STUDENTS_DATA_SUCCESS =
  "FETCH_VARIFIED_STUDENTS_DATA_SUCCESS";
export const FETCH_VARIFIED_STUDENTS_DATA_FAILURE =
  "FETCH_VARIFIED_STUDENTS_DATA_FAILURE";

//Fetch student details
export const FETCH_STUDENTS_DETAILS = "FETCH_STUDENTS_DETAILS";
export const FETCH_STUDENTS_DETAILS_SUCCESS = "FETCH_STUDENTS_DETAILS_SUCCESS";
export const FETCH_STUDENTS_DETAILS_FAILURE = "FETCH_STUDENTS_DETAILS_FAILURE";
